name: "Client Tests"
on: [push, pull_request]
jobs:

  test-client-ubuntu:
    name: "Client Tests: Ubuntu"
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash

    - name: Check out code
      uses: actions/checkout@v1
      with:
        path: src/github.com/juju/juju

    - name: Install mongo dependencies
      run: |
        make install-mongo-dependencies

    - name: Install vendor dependencies
      run: |
        make dep
      shell: bash

    - name: Test client
      run: |
        go test -v ./cmd/... -check.v
